### ISSUE TITLE
两个无伤大雅的小问题

### ISSUE THREAD

**Issue by ChangboBro** [zhcong/ST7302-for-micropython#1]
1. main.py 中字符串应该是hello world而不是hello word吧😂
2. Screen.py中这个屏幕的驱动是ST7302来着，咋写成ST7032了捏😨

另外非常感谢作者的工作，我还没有仔细看这个屏幕的datasheet，感觉和ssd1306、st7567这样的屏幕区别好大哦，等我有空了会尝试改进一下，不知道能不能fork，哈哈

**Comment by zhcong** [comment]
> 

感谢指出，已修改
相关文档已上传，欢迎优化
