### ISSUE TITLE
Screen.py是否缺少部分函数？

### ISSUE THREAD

**Issue by Lzy315** [zhcong/ST7302-for-micropython#2]

**Comment by Lzy315** [comment]
在Screen.py中未找到以下函数：
screen.text('hello word', 5, 5)
screen.fill_rect(5, 20, 10, 20, 1)
screen.text('hello2 word2', 150, 50)
screen.line(5,50,220,100,1)
screen.flush_buffer()
能否上传，感谢！

**Comment by zhcong** [comment]
> 

这些方法是继承自`framebuf.FrameBuffer`，是Micropython库里标准函数，详见：[Micropython文档](https://docs.micropython.org/en/latest/library/framebuf.html)

**Comment by zhcong** [comment]
已解答
